"""initial

Revision ID: 14611de87b66
Revises: 
Create Date: 2026-07-28 09:54:08.268508
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '14611de87b66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_kind'), 'assets', ['kind'], unique=False)
    op.create_index('uq_asset_sha256', 'assets', ['sha256'], unique=True, postgresql_where=sa.text('sha256 IS NOT NULL'))
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('cefr', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_patterns',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label_es', sa.Text(), nullable=False),
    sa.Column('explanation_es', sa.Text(), nullable=False),
    sa.Column('minimal_pairs', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('headwords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lemma', sa.Text(), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('freq_rank', sa.Integer(), nullable=True),
    sa.Column('ipa_us', sa.Text(), nullable=True),
    sa.Column('ipa_uk', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma', 'pos', name='uq_headword')
    )
    op.create_index(op.f('ix_headwords_lemma'), 'headwords', ['lemma'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'idx', name='uq_chapter_idx')
    )
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_id', sa.BigInteger(), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_es', sa.Text(), nullable=True),
    sa.Column('cefr', sa.String(length=4), nullable=True),
    sa.Column('tsv_en', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text_en)", persisted=True), nullable=True),
    sa.Column('tsv_es', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', coalesce(text_es, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_chapter_id'), 'sentences', ['chapter_id'], unique=False)
    op.create_index('ix_sentences_tsv_en', 'sentences', ['tsv_en'], unique=False, postgresql_using='gin')
    op.create_index('ix_sentences_tsv_es', 'sentences', ['tsv_es'], unique=False, postgresql_using='gin')
    op.create_index('uq_sentence_position', 'sentences', ['chapter_id', 'idx'], unique=True, postgresql_where=sa.text('chapter_id IS NOT NULL'))
    op.create_table('attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('audio_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('expected_text', sa.Text(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('prosody_score', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_engine'), 'attempts', ['engine'], unique=False)
    op.create_index('ix_attempts_raw', 'attempts', ['raw'], unique=False, postgresql_using='gin')
    op.create_index('ix_attempts_recorded_at', 'attempts', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_attempts_sentence_id'), 'attempts', ['sentence_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('lemma', sa.Text(), nullable=True),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('headword_id', sa.BigInteger(), nullable=True),
    sa.Column('expected_ipa', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['headword_id'], ['headwords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence_id', 'idx', name='uq_token_idx')
    )
    op.create_index(op.f('ix_tokens_sentence_id'), 'tokens', ['sentence_id'], unique=False)
    op.create_table('word_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=24), nullable=False),
    sa.Column('stress_ok', sa.Boolean(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'word_index', name='uq_word_score_position')
    )
    op.create_index(op.f('ix_word_scores_attempt_id'), 'word_scores', ['attempt_id'], unique=False)
    op.create_table('phoneme_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word_score_id', sa.BigInteger(), nullable=False),
    sa.Column('phoneme_index', sa.Integer(), nullable=False),
    sa.Column('expected_ipa', sa.String(length=8), nullable=False),
    sa.Column('produced_ipa', sa.String(length=8), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['word_score_id'], ['word_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_score_id', 'phoneme_index', name='uq_phoneme_score_position')
    )
    op.create_index('ix_phoneme_expected', 'phoneme_scores', ['expected_ipa'], unique=False)
    op.create_index(op.f('ix_phoneme_scores_word_score_id'), 'phoneme_scores', ['word_score_id'], unique=False)
    op.create_table('pattern_hits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word_score_id', sa.BigInteger(), nullable=False),
    sa.Column('phoneme_score_id', sa.BigInteger(), nullable=True),
    sa.Column('pattern_code', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_code'], ['error_patterns.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phoneme_score_id'], ['phoneme_scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['word_score_id'], ['word_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pattern_hits_code', 'pattern_hits', ['pattern_code'], unique=False)
    op.create_index(op.f('ix_pattern_hits_word_score_id'), 'pattern_hits', ['word_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_hits_word_score_id'), table_name='pattern_hits')
    op.drop_index('ix_pattern_hits_code', table_name='pattern_hits')
    op.drop_table('pattern_hits')
    op.drop_index(op.f('ix_phoneme_scores_word_score_id'), table_name='phoneme_scores')
    op.drop_index('ix_phoneme_expected', table_name='phoneme_scores')
    op.drop_table('phoneme_scores')
    op.drop_index(op.f('ix_word_scores_attempt_id'), table_name='word_scores')
    op.drop_table('word_scores')
    op.drop_index(op.f('ix_tokens_sentence_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_attempts_sentence_id'), table_name='attempts')
    op.drop_index('ix_attempts_recorded_at', table_name='attempts')
    op.drop_index('ix_attempts_raw', table_name='attempts', postgresql_using='gin')
    op.drop_index(op.f('ix_attempts_engine'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('uq_sentence_position', table_name='sentences', postgresql_where=sa.text('chapter_id IS NOT NULL'))
    op.drop_index('ix_sentences_tsv_es', table_name='sentences', postgresql_using='gin')
    op.drop_index('ix_sentences_tsv_en', table_name='sentences', postgresql_using='gin')
    op.drop_index(op.f('ix_sentences_chapter_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_headwords_lemma'), table_name='headwords')
    op.drop_table('headwords')
    op.drop_table('error_patterns')
    op.drop_table('books')
    op.drop_index('uq_asset_sha256', table_name='assets', postgresql_where=sa.text('sha256 IS NOT NULL'))
    op.drop_index(op.f('ix_assets_kind'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
