"""paragraph structure

Revision ID: 231dd49570b3
Revises: 14611de87b66
Create Date: 2026-07-28 14:13:32.178693
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '231dd49570b3'
down_revision = '14611de87b66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` es solo para rellenar las filas que ya existen: sin el,
    # ALTER TABLE ... NOT NULL falla sobre una tabla con datos. Se retira
    # despues para que la aplicacion siga siendo la duena del valor por
    # defecto y no quede una regla de negocio escondida en el esquema.
    #
    # El relleno con 0 es un marcador, no la estructura real: las oraciones ya
    # importadas no saben a que parrafo pertenecian. Hay que reimportar el
    # libro para recuperarla.
    op.add_column(
        'sentences',
        sa.Column('paragraph_idx', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'sentences',
        sa.Column('is_heading', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('sentences', 'paragraph_idx', server_default=None)
    op.alter_column('sentences', 'is_heading', server_default=None)
    op.create_index(op.f('ix_sentences_paragraph_idx'), 'sentences', ['paragraph_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentences_paragraph_idx'), table_name='sentences')
    op.drop_column('sentences', 'is_heading')
    op.drop_column('sentences', 'paragraph_idx')
    # ### end Alembic commands ###
