"""gloss cache

Revision ID: 891079683a8d
Revises: edeae46dafa3
Create Date: 2026-07-29 09:05:05.574223
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '891079683a8d'
down_revision = 'edeae46dafa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glosses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('surface_lower', sa.String(length=64), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=True),
    sa.Column('lemma', sa.String(length=64), nullable=False),
    sa.Column('pos', sa.String(length=24), nullable=False),
    sa.Column('sense_es', sa.Text(), nullable=False),
    sa.Column('note_es', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('lookups', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surface_lower', 'sentence_id', name='uq_gloss_in_context')
    )
    op.create_index(op.f('ix_glosses_sentence_id'), 'glosses', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_glosses_surface_lower'), 'glosses', ['surface_lower'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glosses_surface_lower'), table_name='glosses')
    op.drop_index(op.f('ix_glosses_sentence_id'), table_name='glosses')
    op.drop_table('glosses')
    # ### end Alembic commands ###
