"""reading progress

Revision ID: edeae46dafa3
Revises: 231dd49570b3
Create Date: 2026-07-29 08:41:24.540863
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'edeae46dafa3'
down_revision = '231dd49570b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_progress',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('last_sentence_id', sa.BigInteger(), nullable=True),
    sa.Column('furthest_idx', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_sentence_id'], ['sentences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_progress_chapter_id'), 'reading_progress', ['chapter_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_progress_chapter_id'), table_name='reading_progress')
    op.drop_table('reading_progress')
    # ### end Alembic commands ###
